### ISSUE TITLE
Shiny app doesn't work properly

### ISSUE THREAD

**Issue by biga94** [BiodataAnalysisGroup/metaDIEA#1]
Hey there, I'd like to try your Shiny app but unfortunately this error comes out:

Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
[1] "Kallisto - Sleuth..."
[1] "Tophat2 - Cufflinks..."
[1] "Hisat2 - DESeq2...."
[1] "BitSeq..."
Warning in read.table(file = "./data/IsoMat.de.txt", fill = TRUE, sep = "\t",  :
  header and 'col.names' are of different lengths
[1] "RSEM..."
Warning in read.table(file = "./data/EBSeq.Simulated.All.Out.FC.txt", fill = TRUE,  :
  header and 'col.names' are of different lengths
Warning in read.table(file = "./data/EBSeq.Simulated.DE.Out.txt", fill = TRUE,  :
  header and 'col.names' are of different lengths
[1] "EBSeq..."
Error in aggregate.formula(formula = V5 ~ Id, data = simData, FUN = sum) : 
  argument 'x' is  missing -- it has been renamed from 'formula'

Any suggestion? 
Best,

Davide

**Comment by aspaor** [comment]
Hi @biga94                                

Thank you for your clarification.
We have updated the source code in order  Shiny runs properly. Don't hesitate to contact us for any further inquiry.

Kind regards,
Aspa

**Comment by biga94** [comment]
Thank you too for the quick response! It works properly :-)

Best wishes,
Davide
